# -*- coding: utf-8 -*-
"""Project_Customer_Churn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_kwg0W02TyqTbPi19K2A2Wl20sEa3XK6

#Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/class_customer_churn.csv')

"""#Inspect Data"""

df.head()

pip install ydata-profiling

from ydata_profiling import ProfileReport
ProfileReport(df)

df.describe().round(2)



"""#**Feature Engineering**



"""

df = df.drop(columns=['RowNumber','CustomerId','Surname'], axis=1, errors='ignore')

df['Gender'] = df['Gender'].map({'Male':1,'Female':0})

df = pd.get_dummies(df, columns=['Geography'], drop_first=True)

numerical_cols = ['CreditScore', 'Balance', 'EstimatedSalary', 'Age', 'Tenure','NumOfProducts','HasCrCard','IsActiveMember']
for col in numerical_cols:
    sns.boxplot(x=df[col])
    plt.show()

X = df.drop(['Exited'], axis=1)
y = df['Exited']

X.shape
y.value_counts(normalize=True)

"""#**Model Selection**



1.  SVM
2.  KNN
3.  Random Forest

#**Model Building & Training**
"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

"""#**SVM**"""

from sklearn.svm import SVC
svm_model = SVC()
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

y_pred_svm

y_test.values

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_svm)

"""#**KNN**"""

from sklearn.neighbors import KNeighborsClassifier
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

accuracy_score(y_test, y_pred_knn)

"""#**Random Froest**"""

from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)

accuracy_score(y_test, y_pred_rf)

"""#**Featuer Importance**"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

feature_importance = pd.Series(rf_model.feature_importances_, index=X_train.columns).sort_values(ascending=False)
feature_importance.head(10)

feature_importance.plot(kind='bar', figsize=(10,6))
plt.title('Top 10 Feature Importance')
plt.xlabel('Features')
plt.ylabel('Importance')
plt.show()

"""#**Model Deployment**"""

import joblib
joblib.dump(rf_model, 'rf_model.pkl')

pip install gradio

import gradio as gr
import pandas as pd
import joblib

# Load the trained Random Forest model
rf_model = joblib.load('rf_model.pkl')

# Define the prediction function
def predict_churn(CreditScore, Geography, Gender, Age, Tenure, Balance,
                  NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary):

    # Preprocessing for Gender
    gender_mapped = 1 if Gender == 'Male' else 0

    # Preprocessing for Geography (One-hot encoding, matching model's trained columns)
    geo_germany = 1 if Geography == 'Germany' else 0
    geo_spain = 1 if Geography == 'Spain' else 0

    # Create a DataFrame from the input features, ensuring correct column order
    # This order must match the X_train used during model training
    input_df = pd.DataFrame([[CreditScore, gender_mapped, Age, Tenure, Balance,
                              NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary,
                              geo_germany, geo_spain]],
                            columns=['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance',
                                     'NumOfProducts', 'HasCrCard', 'IsActiveMember',
                                     'EstimatedSalary', 'Geography_Germany', 'Geography_Spain'])

    # Make prediction
    prediction = rf_model.predict(input_df)[0]
    prediction_proba = rf_model.predict_proba(input_df)[0]

    if prediction == 1:
        return f"The customer is likely to churn. (Probability: {prediction_proba[1]:.2f})"
    else:
        return f"The customer is likely to stay. (Probability: {prediction_proba[0]:.2f})"

# Define Gradio input components
inputs = [
    gr.Slider(minimum=350, maximum=850, step=1, value=650, label="Credit Score"),
    gr.Radio(["France", "Germany", "Spain"], value="France", label="Geography"),
    gr.Radio(["Male", "Female"], value="Male", label="Gender"),
    gr.Slider(minimum=18, maximum=92, step=1, value=35, label="Age"),
    gr.Slider(minimum=0, maximum=10, step=1, value=5, label="Tenure (Years)"),
    gr.Number(value=0.0, label="Balance"),
    gr.Slider(minimum=1, maximum=4, step=1, value=1, label="Number of Products"),
    gr.Radio([0, 1], value=1, label="Has Credit Card (0=No, 1=Yes)"),
    gr.Radio([0, 1], value=1, label="Is Active Member (0=No, 1=Yes)"),
    gr.Number(value=50000.0, label="Estimated Salary")
]

# Define Gradio output component
output = gr.Textbox(label="Prediction Result")

# Create and launch the Gradio interface
gr.Interface(
    fn=predict_churn,
    inputs=inputs,
    outputs=output,
    title="Customer Churn Prediction",
    description="Predict if a customer will churn based on their details."
).launch(share=True)